In [1]:
import pandas as pd

# Data from the provided table
data = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    "Nama": ["Budi", "Ani", "Amir", "Siti", "Joko", "Dina", "Arif", "Wati", "Andi", "Rini", 
             "Tono", "Lestari", "Rahmat", "Putri", "Eka", "Farah", "Zaki", "Ika", "Ahmad", "Desi"],
    "Umur": [25, 20, 29, 23, 30, 27, 35, 24, 28, 22, 31, 26, 29, 21, 33, 27, 25, 32, 30, 23],
    "Kota": ["Jakarta", "Bandung", "Surabaya", "Yogyakarta", "Jakarta", "Bandung", "Surabaya", "Jakarta", "Bandung",
             "Yogyakarta", "Jakarta", "Bali", "Jakarta", "Bandung", "Surabaya", "Jakarta", "Bali", "Yogyakarta",
             "Jakarta", "Bandung"],
    "Pekerjaan": ["IT Developer", "Mahasiswa", "Data Scientist", "Graphic Designer", "Software Engineer", "Product Manager", 
                  "System Analyst", "Content Creator", "Database Administrator", "Digital Marketer", "Network Engineer",
                  "UI/UX Designer", "DevOps Engineer", "Mahasiswa", "Backend Developer", "Scrum Master", 
                  "Full Stack Developer", "Machine Learning Engineer", "IT Support", "QA Engineer"],
    "Pendidikan": ["S1 Teknik", "S1 Informatika", "S2 Data Science", "S1 Desain", "S1 Teknik", "S2 Manajemen", 
                   "S1 Teknik", "D3 Komunikasi", "S1 Teknik", "S1 Pemasaran", "S1 Teknik", "S1 Desain", "S1 Teknik",
                   "S1 Informatika", "S1 Teknik", "S2 Manajemen", "S1 Teknik", "S2 Data Science", "D3 Teknik", 
                   "S1 Teknik"],
    "Pengalaman Kerja (tahun)": [3, 0, 5, 2, 6, 8, 10, 1, 4, 2, 7, 4, 5, 0, 9, 6, 4, 8, 6, 2],
    "Sertifikasi": ["AWS, Azure", "None", "TensorFlow", "Adobe CC", "None", "PMP", "ITIL", "SEO, SEM", "Oracle DB", 
                    "Google Ads", "Cisco CCNA", "Figma, Sketch", "Docker, Kubernetes", "None", "Python, Node.js", 
                    "Agile, Scrum Alliance", "React, JavaScript", "Scikit-learn, PyTorch", "CompTIA A+, Linux+", "ISTQB"],
    "Tanggal Bergabung": ["2020-02-15", "2023-08-01", "2018-07-10", "2021-06-01", "2017-09-12", "2016-05-20",
                          "2013-11-03", "2022-01-15", "2019-03-01", "2021-12-10", "2015-08-22", "2019-10-10", 
                          "2018-05-15", "2023-09-01", "2012-08-18", "2017-07-22", "2019-11-25", "2016-03-12", 
                          "2015-04-10", "2021-01-25"]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display general information about the DataFrame
df_info = df.info()

df_info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        20 non-null     int64
 1   Nama                      20 non-null     object
 2   Umur                      20 non-null     int64
 3   Kota                      20 non-null     object
 4   Pekerjaan                 20 non-null     object
 5   Pendidikan                20 non-null     object
 6   Pengalaman Kerja (tahun)  20 non-null     int64
 7   Sertifikasi               20 non-null     object
 8   Tanggal Bergabung         20 non-null     object
dtypes: int64(3), object(6)
memory usage: 1.5+ KB

In [2]:
# 1. Buatlah sebuah Pandas DataFrame (sudah dibuat di langkah sebelumnya)

# 2. Informasi umum tentang DataFrame
info_umum = df.info()

# 3. Hitung jumlah karyawan dari masing-masing kota
jumlah_karyawan_per_kota = df['Kota'].value_counts()

# 4. Data orang di bidang Teknik dengan pengalaman kerja lebih dari 5 tahun
bidang_teknik = df[df['Pekerjaan'].str.contains("Engineer|Developer|IT Support|System Analyst|Administrator", case=False) &
                   (df['Pengalaman Kerja (tahun)'] > 5)]

# 5. Data orang dengan gaji lebih dari 12 juta dan memiliki sertifikasi Scrum atau Agile
# Asumsi sertifikasi Scrum atau Agile: baris di kolom "Sertifikasi" yang mengandung kata "Scrum" atau "Agile"
sertifikasi_scrum_agile = df[df['Sertifikasi'].str.contains("Scrum|Agile", case=False)]

# 6. Data Nama, Pekerjaan, dan Kota dari orang yang bergabung antara tahun 2015-2020
df['Tanggal Bergabung'] = pd.to_datetime(df['Tanggal Bergabung'])
periode_bergabung = df[(df['Tanggal Bergabung'].dt.year >= 2015) & (df['Tanggal Bergabung'].dt.year <= 2020)][
    ['Nama', 'Pekerjaan', 'Kota']]

# 7. Tambah kolom "Status"
df['Status'] = df['Umur'].apply(lambda x: "Lajang" if x <= 25 else "Menikah")

# 8. Simpan DataFrame yang dimodifikasi ke file CSV
output_file = "/mnt/data/dataset_karyawan.csv"
df.to_csv(output_file, index=False)

# Display results for verification
info_umum, jumlah_karyawan_per_kota, bidang_teknik, sertifikasi_scrum_agile, periode_bergabung, output_file

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        20 non-null     int64
 1   Nama                      20 non-null     object
 2   Umur                      20 non-null     int64
 3   Kota                      20 non-null     object
 4   Pekerjaan                 20 non-null     object
 5   Pendidikan                20 non-null     object
 6   Pengalaman Kerja (tahun)  20 non-null     int64
 7   Sertifikasi               20 non-null     object
 8   Tanggal Bergabung         20 non-null     object
dtypes: int64(3), object(6)
memory usage: 1.5+ KB

(None,
 Kota
 Jakarta       7
 Bandung       5
 Surabaya      3
 Yogyakarta    3
 Bali          2
 Name: count, dtype: int64,
     ID   Nama  Umur        Kota                  Pekerjaan       Pendidikan  \
 4    5   Joko    30     Jakarta          Software Engineer        S1 Teknik
 6    7   Arif    35    Surabaya             System Analyst        S1 Teknik
 10  11   Tono    31     Jakarta           Network Engineer        S1 Teknik
 14  15    Eka    33    Surabaya          Backend Developer        S1 Teknik
 17  18    Ika    32  Yogyakarta  Machine Learning Engineer  S2 Data Science
 18  19  Ahmad    30     Jakarta                 IT Support        D3 Teknik

     Pengalaman Kerja (tahun)            Sertifikasi Tanggal Bergabung
 4                          6                   None        2017-09-12
 6                         10                   ITIL        2013-11-03
 10                         7             Cisco CCNA        2015-08-22
 14                         9        Python, Node.js        2012-08-18
 17                         8  Scikit-learn, PyTorch        2016-03-12
 18                         6     CompTIA A+, Linux+        2015-04-10  ,
     ID   Nama  Umur     Kota     Pekerjaan    Pendidikan  \
 15  16  Farah    27  Jakarta  Scrum Master  S2 Manajemen

     Pengalaman Kerja (tahun)            Sertifikasi Tanggal Bergabung
 15                         6  Agile, Scrum Alliance        2017-07-22  ,
        Nama                  Pekerjaan        Kota
 0      Budi               IT Developer     Jakarta
 2      Amir             Data Scientist    Surabaya
 4      Joko          Software Engineer     Jakarta
 5      Dina            Product Manager     Bandung
 8      Andi     Database Administrator     Bandung
 10     Tono           Network Engineer     Jakarta
 11  Lestari             UI/UX Designer        Bali
 12   Rahmat            DevOps Engineer     Jakarta
 15    Farah               Scrum Master     Jakarta
 16     Zaki       Full Stack Developer        Bali
 17      Ika  Machine Learning Engineer  Yogyakarta
 18    Ahmad                 IT Support     Jakarta,
 '/mnt/data/dataset_karyawan.csv')